<a href="https://colab.research.google.com/github/JackyBruceIbarra/Linear-Algebra-58020/blob/main/Activity_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ibarra, Jacky Bruce G.
## 58020

#inverse of 3x3 matrix 




In [89]:
import numpy as np
A = np.array([[1,2,-1],[2,5,1],[-1,-2,2]])
print ('Original matrix is:')
print (A)
print ('Inverse of the matrix is:') # FOR INVERSE The value 8 below will be executed, but the value 9 above will result in an error.
print(np.linalg.inv([[1,2,-1],[2,5,1],[-1,-2,2]]))



Original matrix is:
[[ 1  2 -1]
 [ 2  5  1]
 [-1 -2  2]]
Inverse of the matrix is:
[[12. -2.  7.]
 [-5.  1. -3.]
 [ 1.  0.  1.]]


#transpose of 3x3  matrix 

In [91]:
#A = np.array([[1,2,-1],[2,5,1],[-1,-2,2]])
B = np.transpose(A)
print ('Transpose of the Matrix is:')
print (B)

Transpose of the Matrix is:
[[ 1  2 -1]
 [ 2  5 -2]
 [-1  1  2]]
