<a href="https://colab.research.google.com/github/JackyBruceIbarra/Linear-Algebra-58020/blob/main/Determinant_of_Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Ibarra, Jacky Bruce G.
## 58020

In [12]:
import numpy as np
A = np.array([[1,2,-1],[4,6,-2],[-1,3,3]]) # array
print(A) # printing the array to see the result
print ('Determinat matrix is:')
print(np.linalg.det(A)) # result without round
print ('Determinat with roundoff matrix is:')
print(round(np.linalg.det(A))) # to round up the result

[[ 1  2 -1]
 [ 4  6 -2]
 [-1  3  3]]
Determinat matrix is:
-13.999999999999996
Determinat with roundoff matrix is:
-14
