<a href="https://colab.research.google.com/github/JackyBruceIbarra/Linear-Algebra-58020/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#MIDTERM EXAM


Question 1. Create a Python code that displays a square matrix whose length is 5 (10 points)

In [ ]:
import numpy as np
d = np.full((5,5),5)# square matrix
print (d)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


Question 2. Create a Python code that displays a square matrix whose elements below the principal diagonal are zero (10 points)

In [22]:
import numpy as np
e = np.array([1,2,3,4])#array
print ('Array is', e)
print(np.diag(e))#diagnoal the array



Array is [1 2 3 4]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


Question 3. Create a Python code that displays a square matrix which is symmetrical (10 points)

In [ ]:
import numpy as np
x = np.array([[1,2,3],[2,3,3],[3,4,-2]])
print ('Array is', x)#array

w = np.transpose(x)#transposing the array
print ('transpose is', w)

Array is [[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
transpose is [[ 1  2  3]
 [ 2  3  4]
 [ 3  3 -2]]


Question 4. What is the inverse of matrix C? Show your solution by python coding. (20 points)

$$X = \begin{bmatrix}1&2&3\\ 2&3&3\\ 3&4&-2\end{bmatrix}$$

In [ ]:
import numpy as np
C = np.array([[1,2,3],[2,3,3],[3,4,-2]])#array
print(C)
inv_C=np.linalg.inv(C)#inverse
print(inv_C)

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


Question 5. What is the determinant of the given matrix in Question 4? Show your solution by python coding. (20 points)

In [ ]:

C = np.array([[1,2,3],[2,3,3],[3,4,-2]]) # array
print(C) # printing the array to see the result
print ('Determinat matrix is:')
print(np.linalg.det(C)) # result without round
print ('Determinat with roundoff matrix is:')
print(round(np.linalg.det(A))) # to round up the result

Question 6. Find the roots of the linear equations by showing its python codes (30 points)

5X1 + 4X2 + X3 = 3.4

10X1 + 9X2 + 4X3 = 8.8

10X1 + 13X2 + 15X3 = 19.2



In [ ]:
import numpy as np
A = np.array([[5,4,1],[10,9,4],[10,13,15]])
print(A)
inv_A=np.linalg.inv(A)#inverse
print(inv_A)

B = np.array([[3.4],[8.8],[19.2]])#array
print(B)

#AA^-1X = B.A^-1
X = np.dot(inv_A,B)
print(X)

[[ 5  4  1]
 [10  9  4]
 [10 13 15]]
[[ 5.53333333 -3.13333333  0.46666667]
 [-7.33333333  4.33333333 -0.66666667]
 [ 2.66666667 -1.66666667  0.33333333]]
[[ 3.4]
 [ 8.8]
 [19.2]]
[[0.2]
 [0.4]
 [0.8]]
