<a href="https://colab.research.google.com/github/JackyBruceIbarra/Linear-Algebra-58020/blob/main/Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Ibarra, Jacky Bruce G.
## 58020

In [17]:
import numpy as np
W = np.array([[1,-3],[2,-2],[3,1]])
X = np.array([[3,2,1],[-1,2,3],[2,-1,1]])
Y = np.array([[1,2,0],[0,-1,2]])
Z = np.array([[0,1],[2,3]])


#Problem 1

#a. WY

In [8]:
output = np.dot(W,Y) #compute the dot of W and Y
print(output)

[[ 1  5 -6]
 [ 2  6 -4]
 [ 3  5  2]]


#b. Z+Z

In [11]:
R = np.add(Z,Z)
R

array([[0, 2],
       [4, 6]])

#c. 3X

In [18]:
result = 3*X
print (result)

[[ 9  6  3]
 [-3  6  9]
 [ 6 -3  3]]


#Problem 2

#a.The product (YW)2 is not defined



In [19]:
seta = np.dot(Y,W) 
print(seta)

[[ 5 -7]
 [ 4  4]]


In [30]:
A = np.square(seta)
print (A)

[[25 49]
 [16 16]]


#b. WY – X

In [22]:
B = (output)
C = (X)
print (B-C)

[[-2  3 -7]
 [ 3  4 -7]
 [ 1  6  1]]


#c. YW – Z^2

In [33]:
D = (seta)
E = np.square(Z)
print (D-E)

[[ 5 -8]
 [ 0 -5]]
