<a href="https://colab.research.google.com/github/JackyBruceIbarra/Linear-Algebra-58020/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Ibarra, Jacky Bruce G.
##58020

#Question 1. (20 points) Create a 4 x 4 matrix whose diagonal elements are all one (1's). Name it as matrix "C". Show your solutions using Python codes and do not forget to label them on the Text Cell.

In [30]:
import numpy as np
#Create a 4 x 4 diagonal matrix
C = np.array([[1,1,1,1],[1,1,1,1],[1,1,1,1],[1,1,1,1]])
print (C)
F = np.diagonal([[1,1,1,1],[1,1,1,1],[1,1,1,1],[1,1,1,1]])
print (F)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[1 1 1 1]


##Question 2. (20 points) In relation to Question 1, show a solution that doubles all the values of each element. Show your solutions using Python codes and do not forget to label them on the Text Cell.

In [32]:
output = np.square(C)
print(output)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


#Question 3. (10 points) Find the cross-product of matrices, A = [2,7,4] and B = [3,9,8]. Show your solutions using Python codes and do not forget to label them on the Text Cell.

In [17]:
A = np.array ([2,7,4]) 
B = np.array ([3,9,8])
R = np.cross(A,B) 
print (R)

[20 -4 -3]
