<a href="https://colab.research.google.com/github/JackyBruceIbarra/Linear-Algebra-58020/blob/main/Python%20Exercise%201.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Sum = A+B

In [10]:
#Addition of Matrices
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[-1,2,4],[7,4,2]])
print (a+b)

[[ 0  4  7]
 [11  9  8]]


difference1 = A - B

In [11]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[-1,2,4],[7,4,2]])
print (a-b)

[[ 2  0 -1]
 [-3  1  4]]


difference2 = B - B

In [12]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[-1,2,4],[7,4,2]])
print (b-b)

[[0 0 0]
 [0 0 0]]
